image: acastellano/cirunnerdaedaluscore

stages:
    - test

integration_tests:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus sqlite3 wget
        - wget -O - http://repo.daedalus-project.io/repo.daedalus-project.io.gpg-key.pub | apt-key add -
        - echo "deb [ arch=amd64  ] http://repo.daedalus-project.io/ any daedalus" > /etc/apt/sources.list.d/daedalus-project.list
        - apt-get update -qq
        - apt-get install -y libcatalyst-perl libcatalyst-plugin-configloader-perl libcatalyst-plugin-static-simple-perl libcatalyst-action-renderview-perl libcatalyst-view-tt-perl libcatalyst-view-json-perl libcatalyst-plugin-unicode-perl libcatalyst-plugin-authentication-perl libcatalyst-plugin-authorization-roles-perl libnamespace-autoclean-perl libmoose-perl libmoosex-nonmoose-perl libconfig-general-perl libcatalyst-model-adaptor-perl libmoosex-markasmethods-perl libcatalyst-modules-perl libcatalyst-modules-extra-perl libtext-csv-xs-perl libmodule-install-perl libcatalyst-model-adaptor-perl libdbix-class-encodedcolumn-perl libcatalyst-controller-formbuilder-perl libconfig-zomg-perl libterm-readkey-perl libstring-random-perl libdata-password-perl libdbix-class-timestamp-perl libcatalyst-authentication-store-dbix-class-perl libcatalyst-action-rest-perl libdata-password-check-perl libdbix-class-validation-perl libdatetime-format-sqlite-perl libdaedalus-hermes-perl libcatalyst-plugin-configloader-multi-perl libcrypt-jwt-perl libdatetime-format-mysql-perl libnumber-phone-perl
        - apt-get install -y rabbitmq-server
        - service rabbitmq-server start
    script:
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - rm -f /var/tmp/daedalus_core_realms.db
        - perl script/deploy.pl SQLite /var/tmp/daedalus_core_realms.db
        - perl t/script/populate_test_database.pl
        - perl Makefile.PL
        - make
        - make test

cover:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus sqlite3 wget
        - wget -O - http://repo.daedalus-project.io/repo.daedalus-project.io.gpg-key.pub | apt-key add -
        - echo "deb [ arch=amd64  ] http://repo.daedalus-project.io/ any daedalus" > /etc/apt/sources.list.d/daedalus-project.list
        - apt-get update -qq
        - apt-get install -y libcatalyst-perl libcatalyst-plugin-configloader-perl libcatalyst-plugin-static-simple-perl libcatalyst-action-renderview-perl libcatalyst-view-tt-perl libcatalyst-view-json-perl libcatalyst-plugin-unicode-perl libcatalyst-plugin-authentication-perl libcatalyst-plugin-authorization-roles-perl libnamespace-autoclean-perl libmoose-perl libmoosex-nonmoose-perl libconfig-general-perl libcatalyst-model-adaptor-perl libmoosex-markasmethods-perl libcatalyst-modules-perl libcatalyst-modules-extra-perl libtext-csv-xs-perl libmodule-install-perl libcatalyst-model-adaptor-perl libdbix-class-encodedcolumn-perl libcatalyst-controller-formbuilder-perl libconfig-zomg-perl libterm-readkey-perl libstring-random-perl libdata-password-perl libdbix-class-timestamp-perl libcatalyst-authentication-store-dbix-class-perl libcatalyst-action-rest-perl libdata-password-check-perl libdbix-class-validation-perl libdatetime-format-sqlite-perl libdaedalus-hermes-perl libcatalyst-plugin-configloader-multi-perl libcrypt-jwt-perl libdatetime-format-mysql-perl libnumber-phone-perl
        - apt-get install -y rabbitmq-server
        - service rabbitmq-server start
    script:
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - rm -f /var/tmp/daedalus_core_realms.db
        - perl script/deploy.pl SQLite /var/tmp/daedalus_core_realms.db
        - perl t/script/populate_test_database.pl
        - perl Makefile.PL
        - make
        - cover -test
        - cover -report codecov
    coverage: /Total\s+.+\s(\d+\.\d+?)$/
