image: acastellano/cirunnerbionic

stages:
    - test

unit_tests:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus sqlite3 wget
        - apt-get install -y libcatalyst-perl libcatalyst-plugin-configloader-perl libcatalyst-plugin-static-simple-perl libcatalyst-action-renderview-perl libcatalyst-view-tt-perl libcatalyst-view-json-perl libcatalyst-plugin-unicode-perl libcatalyst-plugin-authentication-perl libcatalyst-plugin-authorization-roles-perl libnamespace-autoclean-perl libmoose-perl libmoosex-nonmoose-perl libconfig-general-perl libcatalyst-model-adaptor-perl libmoosex-markasmethods-perl libcatalyst-modules-perl libcatalyst-modules-extra-perl libtext-csv-xs-perl libmodule-install-perl
    script:
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - rm -f /var/tmp/daedalus_core_realms.db
        - perl script/deploy.pl SQLite /var/tmp/daedalus_core_realms.db
        - perl t/script/populate_test_database.pl
        - perl Makefile.PL && make &&  make test
