image: acastellano/cirunnerbionic

stages:
    - test

unit_tests:
    stage: test
    before_script:
        - apt-get update -qq && apt-get install -y gcc make cpanminus sqlite3
    script:
        - perl --version
        - cpanm --quiet --installdeps --notest .
        - rm -f /var/tmp/daedalus_core_realms.db
        - perl script/deploy.pl SQLite /var/tmp/daedalus_core_realms.db
        - perl t/script/populate_test_database.pl
        - perl Makefile.PL && make &&  make test
