stages:
    - test
    - coverage
    - package

integration_tests:
    stage: test
    image: daedalusproject/base_daedaluscore:latest
    before_script:
        - kubectl config set-cluster default --server=$KUBE_URL --certificate-authority=kubernetes/windmaker.pem
        - kubectl config set-credentials gitlab-daedalus-core-deployer --token=$KUBE_TESTING_USER_TOKEN
        - kubectl config set-context default --cluster=default --user=gitlab-daedalus-core-deployer
        - kubectl config use-context default
        - kubectl -n daedalus-core-testing delete -f kubernetes/daedalus-core-testing/testing-environment.yml --ignore-not-found=true
        - kubectl -n daedalus-core-testing delete configmap redis-config --ignore-not-found=true
        - kubectl -n daedalus-core-testing delete configmap rabbitmq-config --ignore-not-found=true
        - kubectl -n daedalus-core-testing create configmap redis-config --from-file kubernetes/config/redis.conf
        - kubectl -n daedalus-core-testing create configmap rabbitmq-config --from-file kubernetes/config/rabbitmq
        - kubectl -n daedalus-core-testing apply -f kubernetes/daedalus-core-testing/testing-environment.yml
        - export GOPATH=/usr/share/gocode
        - bash utils/test_redis.sh redis-daedalus-core-testing 10 20
    script:
        - echo "Hello" | redis-cli -h redis-daedalus-core-testing -x set greeting
        - redis-cli -h redis-daedalus-core-testing get greeting
        - go run kubernetes/utils/send.go
        - go run kubernetes/utils/receive.go
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - perl Makefile.PL
        - make
        - make test
    after_script:
        - kubectl -n daedalus-core-testing delete -f kubernetes/daedalus-core-testing/testing-environment.yml
        - kubectl -n daedalus-core-testing delete configmap redis-config
        - kubectl -n daedalus-core-testing delete configmap rabbitmq-config --ignore-not-found=true

cover:
    stage: coverage
    image: daedalusproject/base_daedaluscore:latest
    before_script:
        - kubectl config set-cluster default --server=$KUBE_URL --certificate-authority=kubernetes/windmaker.pem
        - kubectl config set-credentials gitlab-daedalus-core-deployer --token=$KUBE_TESTING_USER_TOKEN
        - kubectl config set-context default --cluster=default --user=gitlab-daedalus-core-deployer
        - kubectl config use-context default
        - kubectl -n daedalus-core-testing delete -f kubernetes/daedalus-core-testing/testing-environment.yml --ignore-not-found=true
        - kubectl -n daedalus-core-testing delete configmap redis-config --ignore-not-found=true
        - kubectl -n daedalus-core-testing delete configmap rabbitmq-config --ignore-not-found=true
        - kubectl -n daedalus-core-testing create configmap redis-config --from-file kubernetes/config/redis.conf
        - kubectl -n daedalus-core-testing create configmap rabbitmq-config --from-file kubernetes/config/rabbitmq
        - kubectl -n daedalus-core-testing apply -f kubernetes/daedalus-core-testing/testing-environment.yml
        - export GOPATH=/usr/share/gocode
        - bash utils/test_redis.sh redis-daedalus-core-testing 5 5
    script:
        - echo "Hello" | redis-cli -h redis-daedalus-core-testing -x set greeting
        - redis-cli -h redis-daedalus-core-develop get greeting
        - go run kubernetes/utils/send.go
        - go run kubernetes/utils/receive.go
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - perl Makefile.PL
        - make
        - cover -test
        - cover -report codecov
    coverage: /Total\s+.+\s(\d+\.\d+?)$/
    after_script:
        - kubectl -n daedalus-core-testing delete -f kubernetes/daedalus-core-testing/testing-environment.yml
        - kubectl -n daedalus-core-testing delete configmap redis-config
        - kubectl -n daedalus-core-testing delete configmap rabbitmq-config --ignore-not-found=true

create_package:
    stage: package
    image: daedalusproject/base_deb_perl_builder:201903280602
    script:
        - DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -uc -b
        - mkdir packages
        - mv ../libdaedalus-core-perl*.deb packages/
    artifacts:
        paths:
        - packages
        expire_in: 5 minutes
