stages:
    - deploy

develop_environment:
    stage: deploy
    image: daedalusproject/base_kubectl
    script:
        - openssl enc  -aes-256-cbc -a -k "$OPENSSL_CRYPT_KEY" -d -in kubernetes/config/daedalus-core/secrets/encoded_secret -out kubernetes/config/daedalus-core/secrets/encoded_secret
        - rm -f kubernetes/config/daedalus-core/secrets/encoded_secret
        - cat kubernetes/config/daedalus-core/secrets/secret
        - exit 1
        - declare -a -g REQUIRED_VARIABLES
        - REQUIRED_VARIABLES=( 'ENV_TYPE' 'KUBERNETES_URL' 'KUBERNETES_DEVELOP_USER_NAME' 'KUBERNETES_DEVELOP_USER_TOKEN' 'KUBERNETES_CLUSTER_CRT' 'DAEDALUS_CORE_DEVELOP_NEW_ROOT_PASSWORD' 'DAEDALUS_CORE_DEVELOP_NEW_USER_PASSWORD' 'KUBE_CDIR')
        - ENV_TYPE="develop"
        - source utils/create_environment.sh
        - create_kube_config
        - delete_env_and_configs
        - create_env_and_configs
        - bash utils/test_redis.sh $REDIS_SERVICE 5 10
    tags:
    - kubernetes
