image: acastellano/cirunnerdaedaluscore

stages:
    - test
    - coverage

integration_tests:
    stage: test
    image: daedalusproject/base_daedaluscore:201904161844
    before_script:
        - kubectl config set-cluster default --server=$KUBE_URL --certificate-authority=kubernetes/windmaker.pem
        - kubectl config set-credentials gitlab-daedalus-core-deployer --token=$KUBE_DEVELOP_USER_TOKEN
        - kubectl config set-context default --cluster=default --user=gitlab-daedalus-core-deployer
        - kubectl config use-context default
        - kubectl -n daedalus-core-develop delete -f kubernetes/daedalus-core-develop/dev-environment.yml --ignore-not-found=true
        - kubectl -n daedalus-core-develop delete configmap redis-config --ignore-not-found=true
        - kubectl -n daedalus-core-develop delete configmap rabbitmq-config --ignore-not-found=true
        - kubectl -n daedalus-core-develop create configmap redis-config --from-file kubernetes/config/redis.conf
        - kubectl -n daedalus-core-develop create configmap rabbitmq-config --from-file kubernetes/config/rabbitmq
        - kubectl -n daedalus-core-develop apply -f kubernetes/daedalus-core-develop/dev-environment.yml
        - export GOPATH=/usr/share/gocode
        - bash utils/test_redis.sh redis-daedalus-core-develop 5 5
    script:
        - echo "Hello" | redis-cli -h redis-daedalus-core-develop -x set greeting
        - redis-cli -h redis-daedalus-core-develop get greeting
        - go run kubernetes/utils/send.go
        - go run kubernetes/utils/receive.go
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - perl Makefile.PL
        - make
        - make test
    after_script:
        - kubectl -n daedalus-core-develop delete -f kubernetes/daedalus-core-develop/dev-environment.yml
        - kubectl -n daedalus-core-develop delete configmap redis-config
        - kubectl -n daedalus-core-develop delete configmap rabbitmq-config --ignore-not-found=true

cover:
    stage: coverage
    image: daedalusproject/base_daedaluscore:201904161844
    before_script:
        - kubectl config set-cluster default --server=$KUBE_URL --certificate-authority=kubernetes/windmaker.pem
        - kubectl config set-credentials gitlab-daedalus-core-deployer --token=$KUBE_DEVELOP_USER_TOKEN
        - kubectl config set-context default --cluster=default --user=gitlab-daedalus-core-deployer
        - kubectl config use-context default
        - kubectl -n daedalus-core-develop delete -f kubernetes/daedalus-core-develop/dev-environment.yml --ignore-not-found=true
        - kubectl -n daedalus-core-develop delete configmap redis-config --ignore-not-found=true
        - kubectl -n daedalus-core-develop delete configmap rabbitmq-config --ignore-not-found=true
        - kubectl -n daedalus-core-develop create configmap redis-config --from-file kubernetes/config/redis.conf
        - kubectl -n daedalus-core-develop create configmap rabbitmq-config --from-file kubernetes/config/rabbitmq
        - kubectl -n daedalus-core-develop apply -f kubernetes/daedalus-core-develop/dev-environment.yml
        - export GOPATH=/usr/share/gocode
        - bash utils/test_redis.sh redis-daedalus-core-develop 5 5
    script:
        - echo "Hello" | redis-cli -h redis-daedalus-core-develop -x set greeting
        - redis-cli -h redis-daedalus-core-develop get greeting
        - go run kubernetes/utils/send.go
        - go run kubernetes/utils/receive.go
        - perl --version
        - cd t && cpanm --quiet --installdeps --notest . && cd ..
        - perl Makefile.PL
        - make
        - cover -test
        - cover -report codecov
    coverage: /Total\s+.+\s(\d+\.\d+?)$/
    after_script:
        - kubectl -n daedalus-core-develop delete -f kubernetes/daedalus-core-develop/dev-environment.yml
        - kubectl -n daedalus-core-develop delete configmap redis-config
        - kubectl -n daedalus-core-develop delete configmap rabbitmq-config --ignore-not-found=true
