language: perl
perl:
    - '5.26'
    - '5.24'
    - '5.22'
script: rm -f /var/tmp/daedalus_core_realms.db && perl script/deploy.pl SQLite /var/tmp/daedalus_core_realms.db && perl t/script/populate_test_database.pl &&  perl Makefile.PL && make && make test
after_success:
    - cover -test
    - cover -report codecov
