language: perl
perl:
    - '5.26'
    - '5.24'
    - '5.22'
    - '5.20'
script: perl script/deploy.pl SQLite t/lib/db/daedalus_core_realms.db; perl t/script/create_test_admin_user.pl;  perl Makefile.PL; make; make test
after_success:
    - cover -test
    - cover -report codecov
