requires 'Devel::Cover::Report::Codecov', 0.22;
requires 'Catalyst::Runtime';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::View::TT';
requires 'Catalyst::View::JSON';
requires 'Catalyst::Plugin::Unicode';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Plugin::Authorization::Roles';
requires 'Catalyst::Plugin::Session::Store::FastMmap';
requires 'Catalyst::Authentication::Store::DBIx::Class';
requires 'Catalyst::Authentication::Credential::HTTP';
requires 'Catalyst::Controller::REST';
requires 'DBIx::Class::EncodedColumn';
requires 'Moose';
requires 'MooseX::NonMoose';
requires 'namespace::autoclean';
requires 'Config::General';
requires 'Module::Install::Catalyst';
requires 'Catalyst::Model::Adaptor';
requires 'Catalyst::View::TT';
requires 'Catalyst::Controller::FormBuilder';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::Session::Store::DBIC';
requires 'Text::CSV_XS';
requires 'Config::ZOMG';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Helper::Model::DBI';
requires 'DBIx::Class::TimeStamp';

recommends 'Pod::Usage';

on test => sub {
    requires 'Test::More',       1.302120;
    requires 'Test::Class',      0.50;
    requires 'Test::MockModule', 0.13;
    requires 'Devel::Mutator',   0.03;
};
