package Daedalus::Core::Model::CoreRealms;

use strict;
use warnings;

use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config( schema_class => 'Daedalus::Core::Schema::CoreRealms', );

our $VERSION = '0.01';

=encoding utf8
=head1 NAME

Daedalus::Core::Model::CoreRealms - Catalyst DBIC Schema Model

=head1 SYNOPSIS

Daedalus Model "CoreRealms"

=head1 DESCRIPTION

Catalyst::Model::DBIC::Schema Model using schema Daedalus::Core::Schema::CoreRealms

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 VERSION

$VERSION

=head1 SUBROUTINES/METHODS
=head1 DIAGNOSTICS
=head1 CONFIGURATION AND ENVIRONMENT
=head1 DEPENDENCIES

See debian/control

=head1 INCOMPATIBILITIES
=head1 BUGS AND LIMITATIONS
=head1 LICENSE AND COPYRIGHT

Copyright 2018-2019 Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>

Copying and distribution of this file, with or without modification, are permitted in any medium without royalty provided the copyright notice and this notice are preserved. This file is offered as-is, without any warranty.

=head1 AUTHOR

Álvaro Castellano Vela, alvaro.castellano.vela@gmail.com,,

=cut

1;
