apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: daedalus-core-develop
  name: daedalus-core-balancer
  labels:
    app: daedalus-core
spec:
  selector:
    matchLabels:
      app: nginx
      role: daedalus-core-balancer
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        role: daedalus-core-balancer
    spec:
      containers:
      - name: daedalus-core-nginx
        image: daedalusproject/daedalus_core_develop_nginx
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  namespace: daedalus-core-develop
  name: daedalus-core-nginx
  labels:
    app: nginx
    role: daedalus-core-balancer
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx
    role: daedalus-core-balancer
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: daedalus-core-develop
  name: daedalus-core-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: api-dev.daedalus-project.io
   http:
     paths:
     - path: /
       backend:
         serviceName: daedalus-core-nginx
         servicePort: 80
 tls:
 - hosts:
   - api-dev.daedalus-project.io
   secretName: daedalus-core-develop-cert
