apiVersion: v1
kind: Pod
metadata:
  name: percona-server
  namespace: daedalus-core-develop
  labels:
    app: percona-server
    tier: bakend
    environment: develop
spec:
  containers:
  - name: percona-server
    image: daedalusproject/base_develop_percona_server
    ports:
    - containerPort: 3306
    lifecycle:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              while [ ! -S /var/run/mysqld/mysqld.sock ];
              do
              sleep 2 ;
              done ;
              /usr/bin/mysql -uroot -pletmein -Bse "ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyNewPass';";
              /usr/bin/mysql -uroot -pMyNewPass -Bse "create databadse daedalus_core_realms";
              /usr/bin/mysql -uroot -pMyNewPass -Bse "CREATE USER 'daedalus'@'%' IDENTIFIED BY 'password';";
              /usr/bin/mysql -uroot -pMyNewPass -Bse "GRANT ALL ON daedalus.* TO 'daedalus'@'%' WITH GRANT OPTION;";
---
apiVersion: v1
kind: Service
metadata:
  name: percona-server
  namespace: daedalus-core-develop
  labels:
    app: percona-server
    environment: develop
    tier: bakend
spec:
  ports:
  - name: access
    port: 3306
  selector:
    app: percona-server
    tier: bakend
    environment: develop
