---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-core-develop
---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-core
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-core
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-core-develop
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-core-develop
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-core-develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-core-deployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-core
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-core
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-core-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: daedalus-core
