requires 'Devel::Cover::Report::Codecov', 0.22;
requires 'Catalyst::Controller::REST';
requires 'DBIx::Class::EncodedColumn';
requires 'Module::Install::Catalyst';
requires 'Catalyst::Model::Adaptor';
requires 'Catalyst::Controller::FormBuilder';
requires 'Catalyst::Plugin::Session';
requires 'Catalyst::Plugin::Session::State::Cookie';
requires 'Catalyst::Plugin::Session::Store::DBIC';
requires 'Text::CSV_XS';
requires 'Config::ZOMG';
requires 'Catalyst::Helper::Model::DBI';
requires 'DBIx::Class::TimeStamp';
requires 'DBIx::Class::Validation';
requires 'Term::ReadKey';
requires 'String::Random';
requires 'Data::Password::Check';

recommends 'Pod::Usage';

on test => sub {
    requires 'Test::More',       1.302120;
    requires 'Test::Class',      0.50;
    requires 'Test::MockModule', 0.13;
    requires 'Devel::Mutator',   0.03;
};
